#if !defined(CONSTR_CONFIG_VERSION_HPP__)
#define CONSTR_CONFIG_VERSION_HPP__

#include "macro.hpp"

#define CONSTR_VERSION_MAJOR 0
#define CONSTR_VERSION_MINOR 1
#define CONSTR_VERSION_PATCH 0

#define CONSTR_VERSION CONSTR_STR(CONSTR_VERSION_MAJOR) "." CONSTR_STR(CONSTR_VERSION_MINOR) "." CONSTR_STR(CONSTR_VERSION_PATCH)

#endif // CONSTR_CONFIG_VERSION_HPP__
